<?php

namespace Wearesho\Bobra\Platon\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Wearesho\Bobra\Platon\EnvironmentConfig;
use Horat1us\Environment\MissingEnvironmentException;

class EnvironmentConfigTest extends TestCase
{
    /** @var EnvironmentConfig */
    protected $config;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->config = new EnvironmentConfig();
    }

    public function testGetUrl()
    {
        $this->assertEquals(
            "https://secure.platononline.com/payment/auth",
            $this->config->getUrl()
        );
    }

    public function testGetKey()
    {
        putenv("PLATON_KEY=maza_faqa");

        $this->assertEquals(
            "maza_faqa",
            $this->config->getKey()
        );
    }

    /**
     * @expectedException \Horat1us\Environment\MissingEnvironmentException::class
     */
    public function testException()
    {
        putenv("PLATON_KEY");

        $this->config->getKey();
        $this->expectException(MissingEnvironmentException::class);
    }

    public function testGetPass()
    {
        putenv("PLATON_PASS=fqn228sht");

        $this->assertEquals(
            "fqn228sht",
            $this->config->getPass()
        );
    }

    public function testGetLanguage()
    {
        $this->assertEquals(
            "ua",
            $this->config->getLanguage()
        );
    }

    public function testGetPayment()
    {
        $this->assertEquals(
            "CC",
            $this->config->getPayment()
        );
    }
}
